version: '3'

services:

  #hello-world-nodejs
  hello-node:
    build: ../hello-world-nodejs
    container_name: helloNode
    networks:
      - app-net
    volumes:
      - ../hello-world-nodejs:/app
    # ports:
    #   - "3000:3000"
    # depends_on:
    #   - hello-nginx
  
  #hello-world-golang
  hello-golang:
    build: ../hello-world-golang
    volumes:
      - ../hello-world-golang:/docker-entrypoint-initdb.d
    container_name: helloGolang
    networks:
      - app-net
    # ports:
    #   - "3002:3002"
    # depends_on:
    #   - hello-nginx
  
  #hello-world-nginx
  hello-nginx:
    build: ../hello-world-nginx
    container_name: helloNginx
    networks:
      - app-net
    ports:
      - "80:18181"
    depends_on:
      - hello-node
      - hello-golang

networks:
  app-net:
    driver: bridge